import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AppHeader from "./_components/AppHeader";


export const metadata: Metadata = {
  title: "Trade Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <AppHeader />
        <main>{children}</main>
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: "#333",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
